# Site settings
title: Your Name
email: Your Email
description: "Your Description"
baseurl: "/jekyll-material"
url: ""
paginate: 4
paginate_path: "page/:num/"

# Social links
facebook: username
twitter: username
instagram: username
google_plus: username
github: username
disqus: username

# Build settings
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
rouge: pygments
